"""PR Comment Bot — posts DevLens analysis results as GitHub PR comments."""

from __future__ import annotations

import os
import httpx

from devlens.analyzer import ReviewResult
from devlens.security import ScanResult


GITHUB_API = "https://api.github.com"

REVIEW_TEMPLATE = """## DevLens Review — PR #{pr_number}

**{verdict_emoji} Verdict:** {verdict}

### Summary
{summary}

### Risk Areas ({risk_count})
{risk_section}

### Safe to Skim ({safe_count})
{safe_section}

---
<sub>Generated by <a href="https://github.com/poseclx/devlens">DevLens</a> — AI-powered PR review assistant</sub>
"""

SECURITY_TEMPLATE = """## DevLens Security Scan — PR #{pr_number}

**Score:** {score}/100 (Grade: {grade}) {score_emoji}

**Files scanned:** {files_scanned}/{total_files}

### Findings Summary
| Severity | Count |
|----------|-------|
| Critical | {critical} |
| High | {high} |
| Medium | {medium} |
| Low | {low} |

{findings_section}

{ai_section}

---
<sub>Generated by <a href="https://github.com/poseclx/devlens">DevLens</a> — Security Scanner</sub>
"""


def _github_headers() -> dict[str, str]:
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        raise EnvironmentError(
            "GITHUB_TOKEN environment variable is required to post PR comments. "
            "Set it with: export GITHUB_TOKEN=ghp_..."
        )
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def post_review_comment(result: ReviewResult, repo: str, pr_number: int) -> str:
    """Post a review result as a PR comment. Returns the comment URL."""
    risk_lines = []
    for item in result.risk_items:
        sev = item.get("severity", "medium").upper()
        emoji = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🔵"}.get(sev, "⚪")
        risk_lines.append(f"| {emoji} {sev} | `{item['file']}` | {item['reason']} |")

    risk_section = "| Severity | File | Reason |\n|----------|------|--------|\n" + "\n".join(risk_lines) if risk_lines else "_No risk areas detected._"

    safe_lines = []
    for item in result.safe_items:
        safe_lines.append(f"- `{item['file']}` — {item['reason']}")
    safe_section = "\n".join(safe_lines) if safe_lines else "_No safe files identified._"

    verdict_lower = result.verdict.lower()
    if "ready" in verdict_lower or "merge" in verdict_lower:
        verdict_emoji = "✅"
    elif "needs changes" in verdict_lower or "needs discussion" in verdict_lower:
        verdict_emoji = "⚠️"
    else:
        verdict_emoji = "📋"

    body = REVIEW_TEMPLATE.format(
        pr_number=pr_number,
        verdict=result.verdict,
        verdict_emoji=verdict_emoji,
        summary=result.summary,
        risk_count=len(result.risk_items),
        risk_section=risk_section,
        safe_count=len(result.safe_items),
        safe_section=safe_section,
    )

    return _post_comment(repo, pr_number, body)


def post_security_comment(result: ScanResult, repo: str, pr_number: int) -> str:
    """Post a security scan result as a PR comment. Returns the comment URL."""
    if result.score >= 90:
        score_emoji = "🟢"
    elif result.score >= 60:
        score_emoji = "🟡"
    else:
        score_emoji = "🔴"

    findings_lines = []
    if result.findings:
        findings_lines.append("### Detailed Findings\n")
        for f in sorted(result.findings, key=lambda x: ["critical", "high", "medium", "low", "info"].index(x.severity.value)):
            sev = f.severity.value.upper()
            emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵"}.get(sev, "⚪")
            findings_lines.append(f"#### {emoji} [{sev}] {f.title}")
            findings_lines.append(f"- **File:** `{f.file}`" + (f" (line {f.line})" if f.line else ""))
            findings_lines.append(f"- **Rule:** `{f.rule_id}`")
            if f.match:
                display = f.match[:60] + "..." if len(f.match) > 60 else f.match
                findings_lines.append(f"- **Match:** `{display}`")
            findings_lines.append(f"- {f.description}")
            if f.suggestion:
                findings_lines.append(f"- **Fix:** {f.suggestion}")
            findings_lines.append("")

    findings_section = "\n".join(findings_lines) if findings_lines else "_No security issues found! Your code looks clean._"

    ai_section = ""
    if result.ai_summary:
        ai_section = f"### AI Security Assessment\n\n{result.ai_summary}"

    body = SECURITY_TEMPLATE.format(
        pr_number=result.pr_number,
        score=result.score,
        grade=result.grade,
        score_emoji=score_emoji,
        files_scanned=result.files_scanned,
        total_files=result.total_files,
        critical=result.critical_count,
        high=result.high_count,
        medium=result.medium_count,
        low=result.low_count,
        findings_section=findings_section,
        ai_section=ai_section,
    )

    return _post_comment(repo, pr_number, body)


def _post_comment(repo: str, pr_number: int, body: str) -> str:
    """Post a comment on a GitHub PR issue. Returns the HTML URL of the comment."""
    headers = _github_headers()

    with httpx.Client(headers=headers, timeout=30) as client:
        resp = client.post(
            f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments",
            json={"body": body},
        )
        if resp.status_code == 404:
            raise SystemExit(
                f"\n  Error: PR #{pr_number} not found in '{repo}'.\n"
                f"  Check the repo and PR number.\n"
            )
        if resp.status_code in (401, 403):
            raise SystemExit(
                f"\n  Error: Permission denied posting comment to '{repo}'.\n"
                f"  Make sure your GITHUB_TOKEN has 'repo' or 'public_repo' scope.\n"
            )
        resp.raise_for_status()
        data = resp.json()
        return data.get("html_url", "")
