"""Report generator — Markdown and HTML export for DevLens results.

Generates dashboard-style reports with:
  - Grade badge and score
  - Findings summary table
  - Category breakdown chart (ASCII in MD, CSS in HTML)
  - AI analysis section
  - Metadata (timestamp, PR info)
"""

from __future__ import annotations

import html
import json
from datetime import datetime, timezone
from dataclasses import dataclass
from pathlib import Path

from devlens.analyzer import ReviewResult


@dataclass
class ReportData:
    """Unified data container for report generation."""
    pr_number: int
    pr_title: str
    repo: str
    review: ReviewResult | None = None
    scan_result: object | None = None  # ScanResult (avoid circular import)
    summary: object | None = None      # PRSummary
    timestamp: str = ""

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


# ── Markdown Report ───────────────────────────────────────────

def _severity_icon(severity: str) -> str:
    icons = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}
    return icons.get(severity.lower(), "⚪")


def generate_markdown(data: ReportData) -> str:
    """Generate a full Markdown report."""
    lines = [
        f"# DevLens Report — PR #{data.pr_number}",
        f"**{data.pr_title}**  ",
        f"Repository: `{data.repo}` | Generated: {data.timestamp}",
        "",
        "---",
        "",
    ]

    # Review section
    if data.review:
        r = data.review
        lines.extend([
            "## Code Review",
            "",
            f"**Grade: {r.grade}** | Score: {r.score}/100 | Risk: {r.risk_level}",
            "",
        ])
        if r.findings:
            lines.append("### Findings\n")
            lines.append("| # | Severity | Category | Finding |")
            lines.append("|---|----------|----------|---------|")
            for i, f in enumerate(r.findings, 1):
                sev = f.get("severity", "medium")
                cat = f.get("category", "general")
                title = f.get("title", f.get("finding", ""))
                lines.append(f"| {i} | {_severity_icon(sev)} {sev} | {cat} | {title} |")
            lines.append("")

        if r.summary:
            lines.extend(["### AI Analysis", "", r.summary, ""])

    # Security scan section
    if data.scan_result:
        scan = data.scan_result
        lines.extend([
            "## Security Scan",
            "",
            f"**Grade: {scan.grade}** | Score: {scan.score}/100",
            f"Files scanned: {scan.files_scanned}/{scan.total_files}",
            "",
        ])
        if scan.findings:
            lines.append("### Security Findings\n")
            lines.append("| # | Severity | Rule | File | Description |")
            lines.append("|---|----------|------|------|-------------|")
            for i, f in enumerate(scan.findings, 1):
                lines.append(
                    f"| {i} | {_severity_icon(f.severity.value)} {f.severity.value} "
                    f"| {f.rule_id} | `{f.file}` | {f.title} |"
                )
            lines.append("")

        if scan.ai_summary:
            lines.extend(["### AI Security Assessment", "", scan.ai_summary, ""])

    # Summary section
    if data.summary:
        lines.extend(["## PR Summary", "", data.summary.to_markdown(), ""])

    lines.extend(["---", f"*Generated by [DevLens](https://github.com/poseclx/devlens) v0.3.0*"])

    return "\n".join(lines)


# ── HTML Report ───────────────────────────────────────────────

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DevLens Report — PR #{pr_number}</title>
<style>
  :root {{
    --bg: #0d1117; --surface: #161b22; --border: #30363d;
    --text: #e6edf3; --text-dim: #8b949e; --accent: #58a6ff;
    --green: #3fb950; --yellow: #d29922; --orange: #db6d28; --red: #f85149;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ background: var(--bg); color: var(--text); font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 2rem; line-height: 1.6; }}
  .container {{ max-width: 960px; margin: 0 auto; }}
  h1 {{ font-size: 1.8rem; margin-bottom: 0.5rem; }}
  h2 {{ font-size: 1.3rem; margin: 2rem 0 1rem; color: var(--accent); border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }}
  .meta {{ color: var(--text-dim); font-size: 0.9rem; margin-bottom: 2rem; }}
  .grade-badge {{
    display: inline-flex; align-items: center; justify-content: center;
    width: 64px; height: 64px; border-radius: 50%; font-size: 1.8rem; font-weight: 700;
    margin-right: 1rem; vertical-align: middle;
  }}
  .grade-A {{ background: var(--green); color: #000; }}
  .grade-B {{ background: #56d364; color: #000; }}
  .grade-C {{ background: var(--yellow); color: #000; }}
  .grade-D {{ background: var(--orange); color: #fff; }}
  .grade-F {{ background: var(--red); color: #fff; }}
  .score-row {{ display: flex; align-items: center; gap: 1rem; margin: 1rem 0; }}
  .score-bar {{ flex: 1; height: 8px; background: var(--border); border-radius: 4px; overflow: hidden; }}
  .score-fill {{ height: 100%; border-radius: 4px; transition: width 0.3s; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  th {{ text-align: left; padding: 0.6rem; background: var(--surface); border: 1px solid var(--border); font-size: 0.85rem; color: var(--text-dim); }}
  td {{ padding: 0.6rem; border: 1px solid var(--border); font-size: 0.9rem; }}
  tr:hover {{ background: var(--surface); }}
  .sev {{ display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }}
  .sev-critical {{ background: var(--red); color: #fff; }}
  .sev-high {{ background: var(--orange); color: #fff; }}
  .sev-medium {{ background: var(--yellow); color: #000; }}
  .sev-low {{ background: var(--accent); color: #000; }}
  .sev-info {{ background: var(--border); color: var(--text); }}
  .ai-box {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 1.2rem; margin: 1rem 0; white-space: pre-wrap; }}
  code {{ background: var(--surface); padding: 2px 6px; border-radius: 4px; font-size: 0.85rem; }}
  .footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--text-dim); font-size: 0.8rem; text-align: center; }}
  .footer a {{ color: var(--accent); text-decoration: none; }}
  .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 1rem; margin: 1rem 0; }}
  .stat-card {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; text-align: center; }}
  .stat-value {{ font-size: 1.6rem; font-weight: 700; }}
  .stat-label {{ font-size: 0.8rem; color: var(--text-dim); margin-top: 0.3rem; }}
</style>
</head>
<body>
<div class="container">
  <h1>DevLens Report</h1>
  <p class="meta">PR #{pr_number} — <strong>{pr_title}</strong><br>
    Repository: <code>{repo}</code> | Generated: {timestamp}</p>

  {content}

  <div class="footer">
    Generated by <a href="https://github.com/poseclx/devlens">DevLens</a> v0.3.0
  </div>
</div>
</body>
</html>"""


def _score_color(score: int) -> str:
    if score >= 90: return "var(--green)"
    if score >= 75: return "#56d364"
    if score >= 60: return "var(--yellow)"
    if score >= 40: return "var(--orange)"
    return "var(--red)"


def _grade_letter(grade: str) -> str:
    return grade[0].upper() if grade else "?"


def _sev_html(severity: str) -> str:
    return f'<span class="sev sev-{severity.lower()}">{severity}</span>'


def generate_html(data: ReportData) -> str:
    """Generate a full HTML dashboard report."""
    parts = []

    # Review section
    if data.review:
        r = data.review
        grade_letter = _grade_letter(r.grade)
        color = _score_color(r.score)
        parts.append(f"""
  <h2>Code Review</h2>
  <div class="score-row">
    <div class="grade-badge grade-{grade_letter}">{r.grade}</div>
    <div style="flex:1">
      <div style="font-size:1.1rem">Score: <strong>{r.score}/100</strong> — Risk: {r.risk_level}</div>
      <div class="score-bar"><div class="score-fill" style="width:{r.score}%;background:{color}"></div></div>
    </div>
  </div>""")

        if r.findings:
            rows = ""
            for i, f in enumerate(r.findings, 1):
                sev = f.get("severity", "medium")
                cat = f.get("category", "general")
                title = html.escape(f.get("title", f.get("finding", "")))
                rows += f"<tr><td>{i}</td><td>{_sev_html(sev)}</td><td>{cat}</td><td>{title}</td></tr>\n"
            parts.append(f"""
  <table>
    <thead><tr><th>#</th><th>Severity</th><th>Category</th><th>Finding</th></tr></thead>
    <tbody>{rows}</tbody>
  </table>""")

        if r.summary:
            parts.append(f'<div class="ai-box">{html.escape(r.summary)}</div>')

    # Security section
    if data.scan_result:
        scan = data.scan_result
        grade_letter = _grade_letter(scan.grade)
        color = _score_color(scan.score)
        
        crit = scan.critical_count
        high = scan.high_count
        med = scan.medium_count
        low = scan.low_count
        
        parts.append(f"""
  <h2>Security Scan</h2>
  <div class="score-row">
    <div class="grade-badge grade-{grade_letter}">{scan.grade}</div>
    <div style="flex:1">
      <div style="font-size:1.1rem">Score: <strong>{scan.score}/100</strong></div>
      <div class="score-bar"><div class="score-fill" style="width:{scan.score}%;background:{color}"></div></div>
    </div>
  </div>
  <div class="stats">
    <div class="stat-card"><div class="stat-value" style="color:var(--red)">{crit}</div><div class="stat-label">Critical</div></div>
    <div class="stat-card"><div class="stat-value" style="color:var(--orange)">{high}</div><div class="stat-label">High</div></div>
    <div class="stat-card"><div class="stat-value" style="color:var(--yellow)">{med}</div><div class="stat-label">Medium</div></div>
    <div class="stat-card"><div class="stat-value" style="color:var(--accent)">{low}</div><div class="stat-label">Low</div></div>
    <div class="stat-card"><div class="stat-value">{scan.files_scanned}</div><div class="stat-label">Files Scanned</div></div>
  </div>""")

        if scan.findings:
            rows = ""
            for i, f in enumerate(scan.findings, 1):
                rows += (
                    f"<tr><td>{i}</td><td>{_sev_html(f.severity.value)}</td>"
                    f"<td>{f.rule_id}</td><td><code>{html.escape(f.file)}</code></td>"
                    f"<td>{html.escape(f.title)}</td></tr>\n"
                )
            parts.append(f"""
  <table>
    <thead><tr><th>#</th><th>Severity</th><th>Rule</th><th>File</th><th>Description</th></tr></thead>
    <tbody>{rows}</tbody>
  </table>""")

        if scan.ai_summary:
            parts.append(f'<div class="ai-box">{html.escape(scan.ai_summary)}</div>')

    # Summary section
    if data.summary:
        s = data.summary
        cats = ", ".join(f"<code>{c}</code>" for c in s.categories) if s.categories else "general"
        bullets = "".join(f"<li>{html.escape(c)}</li>" for c in s.key_changes)
        parts.append(f"""
  <h2>PR Summary</h2>
  <p><strong>Categories:</strong> {cats} | <strong>Impact:</strong> {s.impact}</p>
  <p>{html.escape(s.overview)}</p>
  <ul>{bullets}</ul>""")

    content = "\n".join(parts)

    return HTML_TEMPLATE.format(
        pr_number=data.pr_number,
        pr_title=html.escape(data.pr_title),
        repo=html.escape(data.repo),
        timestamp=data.timestamp,
        content=content,
    )


def export_report(
    data: ReportData,
    output_path: str,
    fmt: str = "auto",
) -> str:
    """Export report to file. Returns the path written.
    
    fmt: 'auto' (detect from extension), 'md', 'html'
    """
    path = Path(output_path)

    if fmt == "auto":
        fmt = "html" if path.suffix.lower() in (".html", ".htm") else "md"

    if fmt == "html":
        content = generate_html(data)
    else:
        content = generate_markdown(data)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return str(path)
